using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Transactions;
using Bannerlord.GameMaster.Characters;
using Bannerlord.GameMaster.Heroes;
using Bannerlord.GameMaster.Information;
using Bannerlord.GameMaster.Party;
using NetworkMessages.FromServer;
using SandBox.GauntletUI.AutoGenerated1;
using TaleWorlds.CampaignSystem;
using TaleWorlds.CampaignSystem.Actions;
using TaleWorlds.CampaignSystem.Settlements;
using TaleWorlds.Core;
using TaleWorlds.Localization;
using TaleWorlds.ObjectSystem;

namespace Bannerlord.GameMaster.Clans
{
	/// <summary>
	/// Provides functionality for creating and configuring clans with customizable options.
	/// Uses the new HeroGenerator architecture for reliable hero creation.
	/// </summary>
	public static class ClanGenerator
	{
		/// <summary>
		/// Sets the private _midSettlement field on a clan using reflection.
		/// This is necessary to prevent crashes when the game's AI tries to access FactionMidSettlement.
		/// </summary>
		private static void SetClanMidSettlement(Clan clan, Settlement settlement)
		{
			if (clan == null || settlement == null)
				return;

			try
			{
				// Get the private _midSettlement field using reflection
				FieldInfo midSettlementField = typeof(Clan).GetField("_midSettlement", BindingFlags.NonPublic | BindingFlags.Instance);
				
				if (midSettlementField != null)
				{
					midSettlementField.SetValue(clan, settlement);
				}
			}
			catch (System.Exception ex)
			{
				// Log error but don't crash - the clan can still function without mid settlement
				InfoMessage.Display($"Warning: Failed to set clan mid settlement: {ex.Message}");
			}
		}

		/// MARK: CreateClan
		/// <summary>
		/// Create a new clan with the specified name. The clan will have a party created for its leader filled with troops and companions.<br/>
		/// Optional specify a hero to be moved to the clan and be its leader, defaults to null.
		/// A new hero will be created if hero is null<br/>
		/// Optionally assign clan to kingdom, Kingdom defaults to null (Independent)
		/// </summary>
		/// <param name="name">Name of clan (if null, generates random name from culture)</param>
		/// <param name="leader">Hero to be moved to clan and assigned as it's leader (if null, creates new hero)</param>
		/// <param name="kingdom">Optional: Kingdom to assign clan to, defaults to null (Independent)</param>
		/// <param name="createParty">If true, creates a party for the clan leader (default: true)</param>
		/// <param name="companionCount">Number of companions to add to leader's party (default: 2, 0 to skip)</param>
		/// <param name="cultureFlags">Culture pool for leader creation if leader is null (default: AllMainCultures)</param>
		/// <returns>The created clan</returns>
		public static Clan CreateClan(string name = null, Hero leader = null, Kingdom kingdom = null, bool createParty = true, int companionCount = 2, CultureFlags cultureFlags = CultureFlags.AllMainCultures)
		{
			// Generate clan name if not provided
			if (string.IsNullOrEmpty(name))
			{
				// Use Empire as default culture for name generation if no leader
				CultureObject nameCulture = leader?.Culture ?? CultureLookup.Empire;
				name = CultureLookup.GetUniqueRandomClanName(nameCulture);
			}
			
			TextObject nameObj = new(name);
			string stringId = ObjectManager.Instance.GetUniqueStringId(nameObj, typeof(Clan));
			Clan clan = Clan.CreateClan(stringId);

			TextObject informalNameObj = nameObj;
			clan.ChangeClanName(nameObj, informalNameObj);

			// Set initial culture to determine default party template
			CultureObject initialCulture = leader?.Culture ?? CultureLookup.Empire;
			clan.Culture = initialCulture;
			clan.BasicTroop = initialCulture.BasicTroop;

			// Create leader if not provided - clan now exists so CreateLords can use it
			leader ??= HeroGenerator.CreateLords(1, cultureFlags, GenderFlags.Either, clan, withParties: false, randomFactor: 1f)[0];

			// Clean up any existing party and settlement state if leader was created elsewhere
			HeroGenerator.CleanupHeroState(leader);

			// Assign leader to clan and configure
			leader.Clan = clan;
			leader.SetNewOccupation(Occupation.Lord);
			leader.IsMinorFactionHero = false;
			clan.SetLeader(leader);
			clan.Culture = leader.Culture;
			clan.BasicTroop = leader.Culture.BasicTroop;
			clan.Banner = Banner.CreateRandomClanBanner(RandomNumberGen.Instance.NextRandomInt());

			clan.IsNoble = true;
			clan.IsRebelClan = false;

			// Ensure Clan info is updated
			clan.UpdateFactionsAtWarWith();
			clan.ConsiderAndUpdateHomeSettlement();

			Settlement homeSettlement = leader.GetHomeOrAlternativeSettlement();

			clan.SetInitialHomeSettlement(homeSettlement);
			
			// CRITICAL: Set the mid settlement to prevent crashes when game AI accesses FactionMidSettlement
			// This must be set before clan.Initialize() or when clans join kingdoms
			SetClanMidSettlement(clan, homeSettlement);

			// Create leader's party if requested
			if (createParty && (leader.PartyBelongedTo == null || !leader.IsPartyLeader))
				leader.CreateParty(homeSettlement);

			// Add companions to party if party exists and companions requested
			if (leader.PartyBelongedTo != null && companionCount > 0)
			{
				List<Hero> companions = HeroGenerator.CreateCompanions(companionCount, leader.Culture.ToCultureFlag(), clan: clan, randomFactor: 1);
				leader.PartyBelongedTo.AddCompanionsToParty(companions);
			}

			// Add troops to party if it exists
			if (leader.PartyBelongedTo != null)
			{
				// Add 10 basic, 10 elite, and 10 mercenary troops of the leader's culture
				leader.PartyBelongedTo.AddMixedTierTroops(10);
			}

			// Join Kingdom if specified
			if (kingdom != null)
				ChangeKingdomAction.ApplyByJoinToKingdom(clan, kingdom);

			// Set Clan Tier and related properties
			int targetClanTier = 3;
			clan.SetClanTier(targetClanTier);

			// Gold
			int baseGold = 10000;
			leader.ChangeHeroGold(baseGold * (targetClanTier + 1));

			// Influence
			float baseInfluence = 100;
			clan.Influence += baseInfluence * targetClanTier;
			
			clan.UpdateCurrentStrength();
            clan.Initialize();
			clan.IsReady = true;
			
			return clan;
		}

		/// MARK: GenerateClans
		/// <summary>
		/// Generate multiple clans with random names from culture lists.
		/// Uses the new hero creation architecture to prevent crashes from state conflicts.
		/// </summary>
		/// <param name="count">Number of clans to generate</param>
		/// <param name="cultureFlags">Culture pool to select from (default: AllMainCultures)</param>
		/// <param name="kingdom">Optional kingdom for all clans to join (default: null/Independent)</param>
		/// <param name="createParties">If true, creates parties for clan leaders (default: true)</param>
		/// <param name="companionCount">Number of companions per clan (default: 2)</param>
		/// <returns>List of created clans</returns>
		public static List<Clan> GenerateClans(int count, CultureFlags cultureFlags = CultureFlags.AllMainCultures, Kingdom kingdom = null, bool createParties = true, int companionCount = 2)
		{
			List<Clan> clans = new();
	
			// Create each clan individually, letting CreateClan handle hero creation
			// This ensures each hero is properly initialized with clan association from the start
			for (int i = 0; i < count; i++)
			{
				// Pass null for name and leader to auto-generate
				// CreateClan will create the hero with proper clan association at line 89
				Clan clan = CreateClan(null, null, kingdom, createParties, companionCount, cultureFlags);
				clans.Add(clan);
			}
	
			return clans;
		}

		/// MARK: CreateMinorClan
		/// <summary>
		/// Creates a minor faction clan (not a noble house).
		/// Useful for creating mercenary companies, bandit factions, or other minor groups.
		/// </summary>
		/// <param name="name">Name of the minor clan (if null, generates random name)</param>
		/// <param name="leader">Optional leader hero (creates one if null)</param>
		/// <param name="cultureFlags">Culture for the clan (default: AllMainCultures)</param>
		/// <param name="createParty">If true, creates a party for the leader (default: true)</param>
		/// <returns>The created minor clan</returns>
		public static Clan CreateMinorClan(string name = null, Hero leader = null, CultureFlags cultureFlags = CultureFlags.AllMainCultures, bool createParty = true)
		{
			// Generate clan name if not provided
			if (string.IsNullOrEmpty(name))
			{
				// Use Empire as default culture for name generation if no leader
				CultureObject nameCulture = leader?.Culture ?? CultureLookup.Empire;
				name = CultureLookup.GetUniqueRandomClanName(nameCulture);
			}
			
			TextObject nameObj = new(name);
			string stringId = ObjectManager.Instance.GetUniqueStringId(nameObj, typeof(Clan));
			Clan clan = Clan.CreateClan(stringId);

			TextObject informalNameObj = nameObj;
			clan.ChangeClanName(nameObj, informalNameObj);

			// Set initial culture
			CultureObject initialCulture = leader?.Culture ?? CultureLookup.Empire;
			clan.Culture = initialCulture;
			clan.BasicTroop = initialCulture.BasicTroop;

			// Create leader if not provided - clan now exists so CreateLords can use it
			if (leader == null)
			{
				leader = HeroGenerator.CreateLords(1, cultureFlags, GenderFlags.Either, clan, withParties: false, randomFactor: 1f)[0];
			}
			else
			{
				HeroGenerator.CleanupHeroState(leader);
			}

			// Update culture from leader in case it changed
			clan.Culture = leader.Culture;
			clan.BasicTroop = leader.Culture.BasicTroop;

			// Assign leader to clan
			leader.Clan = clan;
			leader.SetNewOccupation(Occupation.Lord);
			leader.IsMinorFactionHero = true;  // Mark as minor faction
			clan.SetLeader(leader);
			clan.Banner = Banner.CreateRandomClanBanner(RandomNumberGen.Instance.NextRandomInt());

			clan.IsNoble = false;  // Not a noble clan
			clan.IsRebelClan = false;

			clan.UpdateFactionsAtWarWith();
			clan.ConsiderAndUpdateHomeSettlement();

			Settlement homeSettlement = leader.GetHomeOrAlternativeSettlement();
			clan.SetInitialHomeSettlement(homeSettlement);
			
			// CRITICAL: Set the mid settlement to prevent crashes when game AI accesses FactionMidSettlement
			SetClanMidSettlement(clan, homeSettlement);
			
			clan.Initialize();

			// Create party if requested
			if (createParty && (leader.PartyBelongedTo == null || !leader.IsPartyLeader))
			{
				leader.CreateParty(homeSettlement);
				
				// Add basic troops
				if (leader.PartyBelongedTo != null)
				{
					leader.PartyBelongedTo.AddBasicTroops(20);
				}
			}

			// Basic properties for minor clan
			clan.SetClanTier(1);
			leader.ChangeHeroGold(5000);
			clan.Influence = 10;

			clan.UpdateCurrentStrength();
			clan.IsReady = true;

			return clan;
		}
	}
}
