using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Linq;
using System.Transactions;
using Bannerlord.GameMaster.Characters;
using Bannerlord.GameMaster.Heroes;
using Bannerlord.GameMaster.Party;
using NetworkMessages.FromServer;
using SandBox.GauntletUI.AutoGenerated1;
using TaleWorlds.CampaignSystem;
using TaleWorlds.CampaignSystem.Actions;
using TaleWorlds.CampaignSystem.Party;
using TaleWorlds.CampaignSystem.Party.PartyComponents;
using TaleWorlds.CampaignSystem.Settlements;
using TaleWorlds.CampaignSystem.ViewModelCollection.ClanManagement;
using TaleWorlds.Core;
using TaleWorlds.Library;
using TaleWorlds.Localization;
using TaleWorlds.MountAndBlade;
using TaleWorlds.ObjectSystem;

namespace Bannerlord.GameMaster.Clans
{
    public static class ClanGenerator
    {
        // MARK:CreateClan 
        /// <summary>
        /// Create a new clan with the specified name. The clan will have a party created for its leader filled with troops and a couple of generated heroes.<br/>
        /// Optional specify a hero to be moved to the clan and be its leader, defaults to null.
        /// A new hero will be created if hero is null<br/>
        /// Optionally assign clan to kingdom, Kingdom defaults to null (Independent)
        /// </summary>
        /// <param name="name">Name of clan</param>
        /// <param name="hero">Hero to be moved to clan and assigned as it's leader</param>
        /// <param name="kingdom">Optional: Kingdom to assign clan to, defaults to null (Independent)</param>
        /// <returns></returns>
        public static Clan CreateClan(string name, Hero leader = null, Kingdom kingdom = null)
        {
            TextObject nameObj = new(name);

            string stringId = ObjectManager.Instance.GetUniqueStringId(nameObj, typeof(Clan));
            Clan clan = Clan.CreateClan(stringId);

            TextObject informalNameObj = nameObj; // What is the difference of informal name vs name?
            clan.ChangeClanName(nameObj, informalNameObj); // Doesn't need localization keys if the clan is being created by the user themselves

            leader ??= HeroGenerator.CreateHeroesFromRandomTemplates(1, clan: clan, randomFactor: 1)[0]; //Create leader if leader is null

            leader.Clan = clan;           // Hero must be moved to clan before made leader
            leader.SetNewOccupation(Occupation.Lord);
            leader.IsMinorFactionHero = false;
            clan.SetLeader(leader);       // Clan needs a leader
            clan.Culture = leader.Culture;
            clan.BasicTroop = leader.Culture.BasicTroop;
            clan.Banner = Banner.CreateRandomClanBanner(RandomNumberGen.Instance.NextRandomInt());

            clan.IsNoble = true;        // Controls if major clan?
            clan.IsRebelClan = false;   // Ensures it is not a reble clan (Needed?)

            // Ensure Clan info is updated (Is this necesary)
            Settlement homeSettlment = leader.GetHomeOrAlternativeSettlement();
            clan.SetInitialHomeSettlement(homeSettlment);
            clan.UpdateCurrentStrength();
            clan.UpdateFactionsAtWarWith();
            clan.ConsiderAndUpdateHomeSettlement();

            // Create leader of clans party (Party creation method adds trade gold and 10 basic troops)
            if (leader.PartyBelongedTo == null || !leader.IsPartyLeader)
                leader.CreateParty(homeSettlment);

            if (leader.PartyBelongedTo == null)
                return clan; // Party creation failed, something went wrong

            // Add 2 companions to leader's party
            List<Hero> companions = HeroGenerator.CreateHeroesFromRandomTemplates(2, leader.Culture.ToCultureFlag(), clan: clan, occupation: Occupation.Wanderer, randomFactor: 1);
            leader.PartyBelongedTo.AddCompanionsToParty(companions);

            // Add an additional 10 basic, 10 elite, and 10 mercenary troops of the leader's culture
            leader.PartyBelongedTo.AddMixedTierTroops(10);

            // Join Kingdom
            if (kingdom != null)
                ChangeKingdomAction.ApplyByJoinToKingdom(clan, kingdom);

            // Clan Tier (Add required renown to reach target tier)
            int targetClanTier = 3;
            clan.SetClanTier(targetClanTier);

            // Gold
            int baseGold = 10000;
            leader.ChangeHeroGold(baseGold * (targetClanTier + 1));

            // Influence
            float baseInfluence = 100;
            clan.Influence += baseInfluence * targetClanTier;

            //clan.UpdateBannerColor(uint backgroundColor, uint, iconColor); // Maybe change color later?
            //clan.Villages.Add(Village) //Interesting can you change owner of village this way without changing owner of the parent Town/Castle?

            clan.Initialize();      // Is this needed?
            clan.IsReady = true;    // Is this needed?

            return clan;
        }

        /// MARK: GenerateClans
        public static List<Clan> GenerateClans(int count, CultureFlags cultureFlags = CultureFlags.AllMainCultures, Kingdom kingdom = null)
        {
            // Generating leaders here allows culture to be selected for clan, instead of relying on the auto leader gen for null leader of the CreateClan method
            List<Hero> leaders = HeroGenerator.CreateHeroesFromRandomTemplates(count, cultureFlags, randomFactor: 1);

            List<Clan> clans = new();

            foreach (Hero leader in leaders)
            {
                string clanName = CultureLookup.GetUniqueRandomClanName(leader.Culture);            
                clans.Add(CreateClan(clanName, leader, kingdom));
            }

            return clans;
        }
    }
}