using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Linq;
using NetworkMessages.FromServer;
using SandBox.GauntletUI.AutoGenerated1;
using TaleWorlds.CampaignSystem;
using TaleWorlds.CampaignSystem.Party;
using TaleWorlds.CampaignSystem.Party.PartyComponents;
using TaleWorlds.CampaignSystem.Settlements;
using TaleWorlds.CampaignSystem.ViewModelCollection.ClanManagement;
using TaleWorlds.Core;
using TaleWorlds.Library;
using TaleWorlds.Localization;
using TaleWorlds.MountAndBlade;
using TaleWorlds.ObjectSystem;

namespace Bannerlord.GameMaster.Clans
{
    public class ClanGenerator
    {
        private readonly Random _random;

        public ClanGenerator()
        {
            int seed = (int)DateTime.UtcNow.Ticks;
            _random = new Random(seed);
        }

        public ClanGenerator(int seed)
        {
            _random = new Random(seed);
        }

        public Clan CreateClan(string name, Hero hero)
        {
            TextObject nameObj = new(name);

            string stringId = ObjectManager.Instance.GetUniqueStringId(nameObj, typeof(Clan));
            Clan clan = Clan.CreateClan(stringId);

            TextObject informalNameObj = nameObj; // What is the difference of informal name vs name?
            clan.ChangeClanName(nameObj, informalNameObj); // Doesn't need localization keys if the clan is being created by the user themselves
               
            clan.Culture = hero.Culture;
            clan.BasicTroop = hero.Culture.BasicTroop;           
            clan.Banner = Banner.CreateRandomClanBanner(_random.Next());  

            clan.IsNoble = true;        // Controls if major clan?
            hero.Clan = clan;           // Hero must be moved to clan before made leader
            clan.SetLeader(hero);       // Clan needs a leader
            
            int targetClanTier = 3;
            clan.SetClanTier(targetClanTier);

            // Gold
            int baseGold = 10000;
            hero.ChangeHeroGold(baseGold * (targetClanTier+ 1));

            // Influence
            float baseInfluence = 100;
            clan.Influence += baseInfluence * targetClanTier;

            // Ensure Clan info is updated (Is this necesary)
            //clan.SetInitialHomeSettlement(Settlements.SettlementQueries.QuerySettlements("poros")[0]); //Temp Crashes becuse I changed name of poros.
            clan.UpdateCurrentStrength();
            clan.UpdateFactionsAtWarWith();
            clan.ConsiderAndUpdateHomeSettlement();
            //clan.UpdateBannerColor(uint backgroundColor, uint, iconColor); // Maybe change color later?

            //clan.Villages.Add(Village) //Interesting can you change owner of village this way without changing owner of the parent Town/Castle?

            clan.Initialize(); // Is this needed?

            return clan;
        }
    }
}